// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyU-6ZRHaYNT63So0N8t7JvUUN8i6id7Q',
    appId: '1:1005767331412:web:4effa6ef33d144a49827c1',
    messagingSenderId: '1005767331412',
    projectId: 'dsds-c4ba7',
    authDomain: 'dsds-c4ba7.firebaseapp.com',
    storageBucket: 'dsds-c4ba7.firebasestorage.app',
    measurementId: 'G-M880SH8JBD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1sXQoMlb8tFhMVKA8cujqAADpL3BCEL4',
    appId: '1:1005767331412:android:2091f8ed00a3794d9827c1',
    messagingSenderId: '1005767331412',
    projectId: 'dsds-c4ba7',
    storageBucket: 'dsds-c4ba7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4ZAa69TEH_iWrfxL7d5CxNuJXe2CdtDk',
    appId: '1:1005767331412:ios:28d273020fd405cf9827c1',
    messagingSenderId: '1005767331412',
    projectId: 'dsds-c4ba7',
    storageBucket: 'dsds-c4ba7.firebasestorage.app',
    androidClientId: '1005767331412-qmfqs3g172h47n3f34l8cbgeajbfosr8.apps.googleusercontent.com',
    iosClientId: '1005767331412-slmnqs9mommbnjuhj56kstm9st4acrlf.apps.googleusercontent.com',
    iosBundleId: 'com.nutrimate.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4ZAa69TEH_iWrfxL7d5CxNuJXe2CdtDk',
    appId: '1:1005767331412:ios:780e685819b07a2e9827c1',
    messagingSenderId: '1005767331412',
    projectId: 'dsds-c4ba7',
    storageBucket: 'dsds-c4ba7.firebasestorage.app',
    androidClientId: '1005767331412-qmfqs3g172h47n3f34l8cbgeajbfosr8.apps.googleusercontent.com',
    iosClientId: '1005767331412-uobrrfi496qj2rgt3tddvqfrsijgtj57.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyU-6ZRHaYNT63So0N8t7JvUUN8i6id7Q',
    appId: '1:1005767331412:web:0b240f17bc850c219827c1',
    messagingSenderId: '1005767331412',
    projectId: 'dsds-c4ba7',
    authDomain: 'dsds-c4ba7.firebaseapp.com',
    storageBucket: 'dsds-c4ba7.firebasestorage.app',
    measurementId: 'G-Q96B8BKZMY',
  );
}
